# Generated by Django 4.1.7 on 2023-03-26 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_rdv', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rendezvous',
            options={'ordering': ['date'], 'verbose_name': 'rendez-vous', 'verbose_name_plural': 'rendez-vous'},
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='slug',
            field=models.SlugField(default=1, editable=False, unique=True),
            preserve_default=False,
        ),
    ]
