# Generated by Django 4.1.7 on 2023-03-26 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_rdv', '0002_alter_rendezvous_options_rendezvous_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='img',
            field=models.ImageField(blank=True, default='images/default.png', null=True, upload_to='images/'),
        ),
    ]
