# Generated by Django 4.1.7 on 2023-03-26 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_rdv', '0004_rendezvous_commentaire_rendezvous_personne_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
