# Generated by Django 4.1.7 on 2023-03-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_rdv', '0005_rendezvous_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='rendezvous',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
